#!/usr/bin/env bash
# =============================================================================
# lib/aliases.sh — Shell alias injection logic (.bashrc / .zshrc)
# =============================================================================
# Sources config/aliases.conf and injects aliases into the user's shell config.
# Alias blocks are wrapped in guarded markers so re-runs are idempotent.
# =============================================================================

ALIASES_MARKER_BEGIN="# >>> devsetup aliases >>>"
ALIASES_MARKER_END="# <<< devsetup aliases <<<"

# Resolve the user's primary shell RC file
_get_shell_rc() {
    local shell_name
    shell_name="$(basename "${SHELL:-/bin/bash}")"
    case "$shell_name" in
        zsh)  echo "$HOME/.zshrc" ;;
        fish) echo "$HOME/.config/fish/config.fish" ;;
        *)    echo "$HOME/.bashrc" ;;
    esac
}

# Remove any previously injected devsetup alias block
_remove_alias_block() {
    local rc_file="$1"
    if grep -q "$ALIASES_MARKER_BEGIN" "$rc_file" 2>/dev/null; then
        # Use sed to delete from marker begin to marker end (inclusive)
        sed -i "/$ALIASES_MARKER_BEGIN/,/$ALIASES_MARKER_END/d" "$rc_file"
    fi
}

# Build the alias block string from config/aliases.conf
_build_alias_block() {
    local conf_file="$1"
    local block=""
    block+="\n${ALIASES_MARKER_BEGIN}\n"
    block+="# Auto-generated by devsetup on $(date '+%Y-%m-%d %H:%M:%S')\n"

    local current_section=""
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip blank lines and comments starting with #
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        # Section headers: [SectionName]
        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            current_section="${BASH_REMATCH[1]}"
            block+="\n# -- ${current_section} --\n"
            continue
        fi
        # alias KEY=VALUE
        if [[ "$line" =~ ^([a-zA-Z_][a-zA-Z0-9_]*)=(.+)$ ]]; then
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[2]}"
            block+="alias ${key}=${val}\n"
        fi
    done < "$conf_file"

    block+="\n${ALIASES_MARKER_END}\n"
    echo -e "$block"
}

# Inject aliases into the detected shell RC file
inject_aliases() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/aliases.conf"}"
    local rc_file; rc_file="$(_get_shell_rc)"

    if [[ ! -f "$conf_file" ]]; then
        log_warn "Aliases config not found: $conf_file"
        return 1
    fi

    log_step "Injecting aliases into $rc_file"

    # Remove old block first (idempotent)
    _remove_alias_block "$rc_file"

    local alias_block
    alias_block="$(_build_alias_block "$conf_file")"

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        echo -e "[dry-run] Would append to $rc_file:\n$alias_block"
        return 0
    fi

    echo -e "$alias_block" >> "$rc_file"
    log_ok "Aliases injected into $rc_file"
    log_info "Run 'source $rc_file' or open a new terminal to apply."
}

# Remove all devsetup aliases from shell RC
remove_aliases() {
    local rc_file; rc_file="$(_get_shell_rc)"
    if grep -q "$ALIASES_MARKER_BEGIN" "$rc_file" 2>/dev/null; then
        _remove_alias_block "$rc_file"
        log_ok "devsetup aliases removed from $rc_file"
    else
        log_skip "No devsetup aliases found in $rc_file"
    fi
}

# List aliases that would be injected (dry preview)
preview_aliases() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/aliases.conf"}"
    if [[ ! -f "$conf_file" ]]; then
        log_warn "Aliases config not found: $conf_file"; return 1
    fi
    _build_alias_block "$conf_file"
}
