#!/usr/bin/env bash
# =============================================================================
# lib/aliases.sh — Shell alias injection logic (.bashrc / .zshrc / fish)
# =============================================================================
# Sources config/aliases.conf and injects aliases into the user's shell config.
# Alias blocks are wrapped in guarded markers so re-runs are idempotent.
# Supports bash, zsh, and fish shells with correct syntax for each.
# =============================================================================

ALIASES_MARKER_BEGIN="# >>> devsetup aliases >>>"
ALIASES_MARKER_END="# <<< devsetup aliases <<<"

# Resolve the user's primary shell RC file
_get_shell_rc() {
    local shell_name
    shell_name="$(basename "${SHELL:-/bin/bash}")"
    case "$shell_name" in
        zsh)  echo "$HOME/.zshrc" ;;
        fish) echo "$HOME/.config/fish/config.fish" ;;
        *)    echo "$HOME/.bashrc" ;;
    esac
}

_get_shell_type() {
    local shell_name
    shell_name="$(basename "${SHELL:-/bin/bash}")"
    case "$shell_name" in
        fish) echo "fish" ;;
        *)    echo "bash" ;;   # bash and zsh use the same alias syntax
    esac
}

# Remove any previously injected devsetup alias block
_remove_alias_block() {
    local rc_file="$1"
    if [[ ! -f "$rc_file" ]]; then return 0; fi
    if grep -q "$ALIASES_MARKER_BEGIN" "$rc_file" 2>/dev/null; then
        # Use sed to delete from marker begin to marker end (inclusive)
        sed -i "/$ALIASES_MARKER_BEGIN/,/$ALIASES_MARKER_END/d" "$rc_file"
    fi
}

# Build the alias block string from config/aliases.conf
# Supports both bash/zsh and fish syntax
_build_alias_block() {
    local conf_file="$1"
    local shell_type="${2:-bash}"
    local block=""
    block+="\n${ALIASES_MARKER_BEGIN}\n"
    block+="# Auto-generated by devsetup on $(date '+%Y-%m-%d %H:%M:%S')\n"

    local current_section=""
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip blank lines and comments starting with #
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        # Section headers: [SectionName]
        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            current_section="${BASH_REMATCH[1]}"
            block+="\n# -- ${current_section} --\n"
            continue
        fi
        # alias KEY=VALUE
        if [[ "$line" =~ ^([a-zA-Z_][a-zA-Z0-9_]*)=(.+)$ ]]; then
            local key="${BASH_REMATCH[1]}"
            local val="${BASH_REMATCH[2]}"

            if [[ "$shell_type" == "fish" ]]; then
                # Fish uses: alias key 'value' or abbr
                # Strip surrounding quotes from val for fish
                local clean_val="$val"
                clean_val="${clean_val#\'}" ; clean_val="${clean_val%\'}"
                clean_val="${clean_val#\"}" ; clean_val="${clean_val%\"}"
                # Skip function-style aliases for fish (they need different syntax)
                if [[ "$clean_val" == *'() {'* ]]; then
                    block+="# $key skipped (function — use fish function instead)\n"
                else
                    block+="alias $key '$clean_val'\n"
                fi
            else
                block+="alias ${key}=${val}\n"
            fi
        fi
    done < "$conf_file"

    block+="\n${ALIASES_MARKER_END}\n"
    echo -e "$block"
}

# Inject aliases into the detected shell RC file
inject_aliases() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/aliases.conf"}"
    local rc_file; rc_file="$(_get_shell_rc)"
    local shell_type; shell_type="$(_get_shell_type)"

    if [[ ! -f "$conf_file" ]]; then
        log_warn "Aliases config not found: $conf_file"
        return 1
    fi

    # Ensure RC file exists
    if [[ ! -f "$rc_file" ]]; then
        mkdir -p "$(dirname "$rc_file")"
        touch "$rc_file"
    fi

    log_step "Injecting aliases into $rc_file (${shell_type} syntax)"

    # Remove old block first (idempotent)
    _remove_alias_block "$rc_file"

    local alias_block
    alias_block="$(_build_alias_block "$conf_file" "$shell_type")"

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        echo -e "[dry-run] Would append to $rc_file:\n$alias_block"
        return 0
    fi

    echo -e "$alias_block" >> "$rc_file"
    log_ok "Aliases injected into $rc_file (${shell_type} format)"
    log_info "Run 'source $rc_file' or open a new terminal to apply."

    # Also inject into secondary shell if both bash and zsh configs exist
    local secondary_rc=""
    if [[ "$shell_type" != "fish" ]]; then
        if [[ -f "$HOME/.zshrc" && "$rc_file" != "$HOME/.zshrc" ]]; then
            secondary_rc="$HOME/.zshrc"
        elif [[ -f "$HOME/.bashrc" && "$rc_file" != "$HOME/.bashrc" ]]; then
            secondary_rc="$HOME/.bashrc"
        fi
    fi

    if [[ -n "$secondary_rc" ]]; then
        _remove_alias_block "$secondary_rc"
        echo -e "$alias_block" >> "$secondary_rc"
        log_ok "Also injected into $secondary_rc"
    fi
}

# Remove all devsetup aliases from all shell RCs
remove_aliases() {
    local found=false
    for rc_file in "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.config/fish/config.fish"; do
        if [[ -f "$rc_file" ]] && grep -q "$ALIASES_MARKER_BEGIN" "$rc_file" 2>/dev/null; then
            _remove_alias_block "$rc_file"
            log_ok "devsetup aliases removed from $rc_file"
            found=true
        fi
    done
    if [[ "$found" != "true" ]]; then
        log_skip "No devsetup aliases found in any RC file"
    fi
}

# List aliases that would be injected (dry preview)
preview_aliases() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/aliases.conf"}"
    local shell_type; shell_type="$(_get_shell_type)"
    if [[ ! -f "$conf_file" ]]; then
        log_warn "Aliases config not found: $conf_file"; return 1
    fi
    echo "" >&2
    printf "  ${BWHITE}${BOLD}Alias Preview${RESET} ${DIM}(%s syntax for %s)${RESET}\n" "$shell_type" "$(_get_shell_rc)" >&2
    echo "" >&2
    _build_alias_block "$conf_file" "$shell_type"
}
