#!/usr/bin/env bash
# =============================================================================
# lib/scaffold.sh — Project folder scaffolding from config/folders.conf
# =============================================================================
# Reads folders.conf and creates the specified directory tree inside a target
# root directory, placing optional README.md stubs in each folder.
# =============================================================================

# Default project root (overridable by caller)
SCAFFOLD_PROJECT_ROOT="${SCAFFOLD_PROJECT_ROOT:-$HOME/projects}"

# Create directory and an optional README stub
_make_dir() {
    local dir="$1"
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        echo "[dry-run] mkdir -p $dir"
        return 0
    fi
    if [[ -d "$dir" ]]; then
        log_skip "Already exists: $dir"
        return 0
    fi
    mkdir -p "$dir"
    log_ok "Created: $dir"
}

_write_readme_stub() {
    local dir="$1"
    local readme="$dir/README.md"
    [[ -f "$readme" ]] && return 0   # don't overwrite existing
    if [[ "${DRY_RUN:-false}" != "true" ]]; then
        local folder_name; folder_name="$(basename "$dir")"
        cat > "$readme" <<EOF
# ${folder_name}

> Auto-generated by devsetup on $(date '+%Y-%m-%d')
EOF
    else
        echo "[dry-run] touch $readme"
    fi
}

# Parse folders.conf and scaffold the tree
# Format: one path per line; comments with #; blank lines ignored
# Leading ~/ or $PROJECT/ are expanded relative to SCAFFOLD_PROJECT_ROOT
scaffold_project() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/folders.conf"}"
    local root="${2:-$SCAFFOLD_PROJECT_ROOT}"
    local with_readmes="${3:-false}"   # pass "true" to create README stubs

    if [[ ! -f "$conf_file" ]]; then
        log_warn "Folders config not found: $conf_file"
        return 1
    fi

    log_section "Scaffolding Project Structure → $root"

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip blank lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue

        # Expand $PROJECT or $ROOT tokens to actual root
        local resolved
        resolved="${line/\$PROJECT/$root}"
        resolved="${resolved/\$ROOT/$root}"

        # Interpret relative paths as relative to root
        if [[ "$resolved" != /* ]]; then
            resolved="$root/$resolved"
        fi

        _make_dir "$resolved"
        [[ "$with_readmes" == "true" ]] && _write_readme_stub "$resolved"
    done < "$conf_file"

    log_ok "Project structure ready at: $root"
}

# Interactive: prompt user for a project name and scaffold under ~/projects/<name>
scaffold_interactive() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/folders.conf"}"

    echo ""
    read -rp "  Enter project name: " proj_name
    if [[ -z "$proj_name" ]]; then
        log_error "Project name cannot be empty."
        return 1
    fi

    local proj_root="$HOME/projects/$proj_name"
    read -rp "  Create README stubs in each folder? [y/N]: " readmes
    local do_readmes="false"
    [[ "${readmes,,}" == "y" ]] && do_readmes="true"

    scaffold_project "$conf_file" "$proj_root" "$do_readmes"
}

# List the folder structure as a tree-like preview (no creation)
preview_scaffold() {
    local conf_file="${1:-"$(dirname "${BASH_SOURCE[0]}")/../config/folders.conf"}"
    echo ""
    echo "  Folder structure defined in $conf_file:"
    echo ""
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            echo "  📁 ${BASH_REMATCH[1]}"
        else
            echo "     └─ $line"
        fi
    done < "$conf_file"
    echo ""
}
